CREATE SEQUENCE CHURCH_SEQUENCE START WITH 1 INCREMENT BY 1 CACHE 1;
CREATE TABLE CENTRAL (
   
    ID BIGINT NOT NULL DEFAULT nextval('CHURCH_SEQUENCE'),
    UUID UUID NOT NULL,
    
    -- ===== CAMPOS DO CentralEntity =====
    NAME VARCHAR(150) NOT NULL,
    ADDRESS VARCHAR(150),
    PHONE_NUMBER VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150),
    FOUNDING_DATE TIMESTAMP,
    
    
     -- ===== CAMPOS DO LifeCycleEntity =====
    CREATED_BY BIGINT NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    UPDATE_DATE TIMESTAMP,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,

    -- ===== CONSTRAINTS =====
    CONSTRAINT pk_central PRIMARY KEY (ID),
    CONSTRAINT uq_central_01 UNIQUE (UUID),
    CONSTRAINT uq_central_02 UNIQUE (NAME)
);


--script de entidade escola criada no dia 10.03.2026--
CREATE SEQUENCE SCHOOL_SEQUENCE START WITH 1 INCREMENT BY 1 CACHE 1;
CREATE TABLE SCHOOL (
   
    ID BIGINT NOT NULL DEFAULT nextval('SCHOOL_SEQUENCE'),
    UUID UUID NOT NULL,
    
    -- ===== CAMPOS DO sCHOOLEntity =====
    NAME VARCHAR(150) NOT NULL,
    CONTACT VARCHAR(50),
    PHONE_NUMBER VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150),
    ADDRESS VARCHAR(150),
    
    
     -- ===== CAMPOS DO LifeCycleEntity =====
    CREATED_BY BIGINT NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    UPDATE_DATE TIMESTAMP,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,

    -- ===== CONSTRAINTS =====
    CONSTRAINT pk_school PRIMARY KEY (ID),
    CONSTRAINT uq_school_01 UNIQUE (UUID)
);

--ACTUaLIZACAO DO CAMPO nuit -- 10.03.2026
UPDATE TABLE SCHOOL ADD NUIT VARCHAR(20); 






CREATE SEQUENCE MEMBER_SEQUENCE START WITH 1 INCREMENT BY 1 CACHE 1;
CREATE TABLE MEMBER (
   
    ID BIGINT NOT NULL DEFAULT nextval('MEMBER_SEQUENCE'),
    UUID UUID NOT NULL,
    
    -- ===== CAMPOS DO MemberEntity =====
    NAME VARCHAR(150) NOT NULL,
    SURNAME VARCHAR(150),
    GENDER CHAR(1),
    BITHDATE DATE,
    PHONE_NUMBER VARCHAR(30),
    EMAIL VARCHAR(150),
    AGE VARCHAR(50) NOT NULL,
    AGE_RANGE VARCHAR(50) NOT NULL,
    EDUCATION VARCHAR(30),
    CENTRAL_ID BIGINT NOT NULL,
    
     -- ===== CAMPOS DO LifeCycleEntity =====
    CREATED_BY BIGINT NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    UPDATE_DATE TIMESTAMP,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,

    -- ===== CONSTRAINTS =====
    CONSTRAINT pk_member PRIMARY KEY (ID),
    CONSTRAINT fk_member_01 FOREIGN KEY (CENTRAL_ID) REFERENCES CENTRAL(ID),
    CONSTRAINT uq_member_01 UNIQUE (UUID)
);

CREATE SEQUENCE CENTRAL_SEQUENCE START WITH 1 INCREMENT BY 1 CACHE 1;
CREATE TABLE CENTRAL (
   
    ID BIGINT NOT NULL DEFAULT nextval('CENTRAL_SEQUENCE'),
    UUID UUID NOT NULL,
    
    -- ===== CAMPOS DO CentralEntity =====
    NAME VARCHAR(150) NOT NULL,
    ADDRESS VARCHAR(150),
    
     -- ===== CAMPOS DO LifeCycleEntity =====
    CREATED_BY BIGINT NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    UPDATE_DATE TIMESTAMP,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,

    -- ===== CONSTRAINTS =====
    CONSTRAINT pk_central PRIMARY KEY (ID),
    CONSTRAINT uq_central_01 UNIQUE (UUID),
    CONSTRAINT uq_central_02 UNIQUE (NAME)
);

